FROM quay.io/letsencrypt/letsencrypt:latest
ENV UID="1000"
MAINTAINER Eric Vallee (eric_vallee@webificservices.com)
COPY ["./run.py", "/opt/run.py"]
USER $UID
ENTRYPOINT [ "python" ]
CMD [ "-u", "/opt/run.py" ]
