FROM node:4.4.2
ENV UID="1000"
RUN echo "node-app:x:${UID}:${UID}:node-app,,,:/home/node-app:/bin/bash" >> /etc/passwd
RUN echo "node-app:x:${UID}:" >> /etc/group
RUN mkdir /home/node-app
COPY index.js /home/node-app/app/index.js
COPY package.json /home/node-app/app/package.json
WORKDIR /home/node-app/app
RUN npm install && \
    chmod 755 /home/node-app/app/index.js && \
    chmod 755 /home/node-app/app/package.json && \
    chmod -R 755 /home/node-app/app/node_modules && \
    chown -R ${UID}:${UID} /home/node-app
USER $UID
CMD npm start
