app:
  container_name: reverse-proxy
  image: magnitus/reverse-proxy:hapi
  restart: always
  ports:
    - "80:8080"
    - "443:44344"
  links:
    - letsencrypt-server:letsencrypt-server
  volumes:
    - ./routes/routes.js:/home/node-app/app/routes.js
    - letsencrypt_certificates:/etc/letsencrypt/live
letsencrypt-server:
  container_name: letsencrypt-server
  image: magnitus/letsencrypt:server
  restart: always
  expose:
    - "8080"
  volumes:
    - letsencrypt_challenges:/home/node-app/challenge
