FROM magnitus/node-app:4
MAINTAINER Eric Vallee (eric_vallee@webificservices.com)

ENV UID="1000"

COPY ./index.js ${APP_DIR}/
COPY ./package.json ${APP_DIR}/

RUN finalize.sh

RUN mkdir /home/node-app/challenge && chown -R $UID:$UID /home/node-app/challenge

USER $UID

EXPOSE 8080
