app:
  container_name: reverse-proxy
  build: ./app
  restart: always
  ports:
    - "80:8080"
  external_links:
    - letsencrypt-daemon:letsencrypt-daemon
    - letsencrypt-server:letsencrypt-server
  volumes:
    - ./routes/routes.js:/home/node-app/app/routes.js
  volumes_from:
    - letsencrypt-certificates