client:
  container_name: letsencrypt-daemon
  build: ./client
  restart: always
  volumes:
    - ./client/config.ini:/etc/letsencrypt/cli.ini
    - /etc/letsencrypt/live
    - /var/www/html/letsencrypt
