client:
  container_name: letsencrypt-daemon
  build: ./client
  restart: always
  volumes:
    - ./client/config.ini:/etc/letsencrypt/cli.ini
    - /etc/letsencrypt/live
  volumes_from:
    - server
server:
  container_name: letsencrypt-server
  build: ./server
  expose:
   - "8080"
  volumes:
    - ./server/app:/home/node-app/app
    - /home/node-app/.well-known/acme-challenge
