client:
  container_name: letsencrypt-daemon
  build: ./client
  restart: always
  volumes:
    - ./client/config.ini:/etc/letsencrypt/cli.ini
    - /etc/letsencrypt/live
  volumes_from:
    - server
  external_links:
    - reverse-proxy
server:
  container_name: letsencrypt-server
  build: ./server
  restart: always
  expose:
    - "8080"
  volumes:
    - /home/node-app/.well-known/acme-challenge
