client:
  container_name: letsencrypt-client
  image: magnitus/letsencrypt:latest-client
  restart: always
  volumes_from:
    - server
    - certificates
  extra_hosts:
    - "reverse-proxy:172.17.0.1"
  environment:
    - DOMAIN=mydomain.com
    - EXECUTION_DELAY=1
    - RENEWAL_DELAY=30
    - DAEMON_MODE=yes
server:
  container_name: letsencrypt-server
  image: magnitus/letsencrypt:latest-webroot-server
  restart: always
  expose:
    - "8080"
  volumes:
    - /home/node-app/challenge
certificates:
  container_name: letsencrypt-certificates
  image: magnitus/letsencrypt:latest-client
  volumes: 
    - /etc/letsencrypt/live
  entrypoint: /bin/bash
  command: chown -R 1000:1000 /etc/letsencrypt/live