client:
  container_name: letsencrypt-daemon
  build: ./client
  restart: always
  volumes:
    - ./client/config.ini:/etc/letsencrypt/cli.ini
  volumes_from:
    - server
    - certificates
  extra_hosts:
   - "reverse-proxy:172.17.0.1"
server:
  container_name: letsencrypt-server
  build: ./server
  restart: always
  expose:
    - "8080"
  volumes:
    - /home/node-app/challenge
certificates:
  container_name: letsencrypt-certificates
  build: ./client
  volumes: 
    - /etc/letsencrypt/live
  entrypoint: /bin/bash
  command: chown -R 1000:1000 /etc/letsencrypt/live